services:
    librarymanagementapi:
        image: ${DOCKER_REGISTRY-}librarymanagementapi
        build:
          context: .
          dockerfile: LibraryManagementAPI/Dockerfile
        ports:
            - "5050:5100"
        depends_on:
            - seq
        networks:
            - library_network
            - auth_network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5100
            - TZ=America/Mexico_City
        volumes:
            - /etc/localtime:/etc/localtime:ro

    seq:
        image: datalust/seq
        container_name: seq
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
        ports:
            - "8041:80"
        networks:
            - library_network

networks:
  library_network:
    driver: bridge
  auth_network:
    name: authmanager_auth_network
    external: true