services:
    librarymanagementapi:
        image: ${DOCKER_REGISTRY-}librarymanagementapi
        build:
            context: .
            dockerfile: LibraryManagementAPIExercise/Dockerfile
        ports:
            - "5050:5100"
        depends_on:
            - seq
            - keycloak
        networks:
            - library_network
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5100

    seq:
        image: datalust/seq
        container_name: seq
        restart: unless-stopped
        environment:
          - ACCEPT_EULA=Y
        ports:
          - "8041:80"
        networks:
          - library_network

    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak
        restart: unless-stopped
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=bN$IhJBf-2
        ports:
            - "8045:8080"
        volumes:
            - keycloak_data:/opt/keycloak/data
        networks:
            - library_network
        command: start-dev

networks:
  library_network:
    driver: bridge

volumes:
  keycloak_data:
